server:
  port: 2020

spring:
  datasource: 
    url: jdbc:mysql://timesheet.cwuonptnpett.ap-south-1.rds.amazonaws.com:3306/timesheet
    username: dibyapp
    password: Geekyants123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect